name: 02-workflow-events


on:
  #push:
  #pull_request:
  #schedule:
   # - cron: '*/5 * * * *' # Runs every day at midnight
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo event name
        run: | 
          echo "Event name: ${{ github.event_name }} event ."
