name: 05-01-workflow-type

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow runs on pull request events of type closed on the main branch."