name: 05-workflow-event-type-01

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow runs on pull request events of type opened, synchronize, and reopened on the main branch."