name: 05-workflow-event-type-01

on:
  pull_request:
    - types: [ opened, synchronize, reopened ]
  branches:
    - main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo event type
        run:
          echo "Event type: ${{ github.event_name }}"